FROM node:20-alpine AS builder

WORKDIR /app

COPY apps/admin ./apps/admin

WORKDIR /app/apps/admin
RUN npm install
RUN npm run build

FROM nginx:alpine AS runner
COPY --from=builder /app/apps/admin/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
